[build]
  command = "npm install --legacy-peer-deps && npm run build --configuration=production"
  publish = "dist/project"  # <-- reemplaza con el nombre correcto si es distinto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
